version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./MeetSmart
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"


